=== VicarTeam/VicarData/$schemas/BloodRituals.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "level": {
        "type": "number"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "ingredients": {
        "type": "string"
      },
      "execution": {
        "type": "string"
      },
      "system": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "level",
      "name",
      "description",
      "ingredients",
      "execution",
      "system"
    ],
    "additionalProperties": false
  }
}

=== VicarTeam/VicarData/de-DE/BloodRituals.json
[
  {
    "id": 1,
    "level": 1,
    "name": "Wandeln auf den Pfaden des Blutes",
    "description": "Mit diesem Ritual wird die Kraft Ein Sinn für Blut verstärkt, wodurch der Anwender weitere Einzelheiten über das Opfer erkennen kann, vorausgesetzt es handelt sich um einen Vampir.",
    "ingredients": "eine silberne Schale mit dem Blut des Opfers (so viel, wie ein Wallungs-Check hergibt).",
    "execution": "Der Anwender vermischt sein Blut mit dem des Opfers und spricht etwa eine Stunde lang wiederholt die Zauberformel über der Schale.",
    "system": "Ein erfolgreicher Wurf auf die Ritualprobe gestattet dem Anwender, die Generation und den Namen des Opfers und den Namen seines Erzeugers zu erfahren. Ein kritischer Triumph enthüllt dem Anwender auch aktive Blutsbande, denen das Opfer unterworfen ist, sei es als Herr oder Sklave."
  },
  {
    "id": 2,
    "level": 1,
    "name": "Insektenbeine",
    "description": "Der Vampir erlangt die Fähigkeit, sich wie ein groteskes Insekt oder eine Spinne an Wänden festzuhalten.",
    "ingredients": "eine lebende Spinne.",
    "execution": "Der Zaubernde füllt eine Phiole mit seinem eigenen Blut, zerquetscht die Spinne und verrührt den zerquetschten Leib mit dem Blut, bevor er die Mixtur trinkt. (Dadurch wird kein Hunger zurückerstattet.) Der Vampir kann das Ritual nur auf sich selbst wirken, andere erlangen keinen Vorteil aus dem Trinken der Mixtur.",
    "system": "Ein erfolgreich durchgeführtes Ritual verleiht die Fähigkeit, sich eine Szene lang an Wänden und Decken festzuhalten. Bei einem kritischen Triumph hält die Wirkung eine Nacht lang. Der Vampir muss sich mit beiden Händen und Füßen an der Oberfläche festhalten und seine Geschwindigkeit ist halbiert."
  },
  {
    "id": 3,
    "level": 1,
    "name": "Blutstein herstellen",
    "description": "Aus diesem Ritual gewinnt man einen Blutstein, einen magischen Peilsender, dessen Richtung und Entfernung der Thaumaturg stets kennt. Seit die Camarilla der modernen Technologie zusehends entsagt, findet dieses Ritual immer häufiger Anwendung.",
    "ingredients": "ein kleines Stück Eisenerz oder ein kleiner Magnet und ein Liter Blut aus einer beliebigen Quelle in einer silbernen Schüssel.",
    "execution": "Der Anwender mischt sein Blut mit dem Blut in der Schüssel und spricht eine Stunde lang einen Zauberspruch darüber, den er in den folgenden zwei Nächten wiederholt. Das Eisenerz (oder der Magnet) nimmt innerhalb von drei Nächten das Blut auf. Wird das Ritual erfolgreich durchgeführt, erscheint die Flüssigkeit durchsichtig.",
    "system": "Führe am Ende der dritten Nacht die Ritualprobe durch. Bei einem Triumph stimmt sich der Zaubernde auf den Blutstein ein und kann zielsicher die Richtung und Entfernung des Steines spüren. Die Wirkung hält, bis der Blutstein zerstört wird oder eine Woche verstrichen ist. Ein Thaumaturg kann so viele Steine haben und im Auge behalten wie sein Wert in Entschlossenheit beträgt."
  },
  {
    "id": 4,
    "level": 1,
    "name": "Abendfrisches Erwachen",
    "description": "Vor dem Morgengrauen durchgeführt, erlaubt es dieses Ritual des Vampirs, beim Anzeichen von Gefahr zu erwachen, wobei er hellwach ist wie in der Nacht.",
    "ingredients": "die verbrannten Knochen und Federn eines Hahns.",
    "execution": "Der Thaumaturg vermischt die Asche mit seinem eigenen Blut und malt mit der Mixtur einen Kreis um seine Ruhestätte.",
    "system": "Erst bei echter Gefahr wird die Ritualprobe abgelegt. Wird der Vampir tagsüber bedroht, lege die Ritualprobe ab. Bei einem Triumph erwacht der Vampir und ignoriert bis zum Ende der Szene die Nachteile, die er erleiden würde, weil er tagsüber wach ist. Bei einem kritischen Triumph hält die Wirkung bis zum nächsten Morgengrauen."
  },
  {
    "id": 5,
    "level": 1,
    "name": "Schutzzeichen gegen Ghule",
    "description": "Misstrauische Tremere entwarfen dieses Ritual, um sich vor den Lakaien rachsüchtiger Rivalen zu schützen. Dieses Schutzzeichen verwendet die Standardregeln für Schutzzeichen (S. 255).",
    "ingredients": "nur das Blut des Zaubernden, wie vorgeschrieben.",
    "execution": "",
    "system": ""
  },
  {
    "id": 6,
    "level": 2,
    "name": "Verständigung mit dem Erzeuger",
    "description": "Der Thaumaturg verwendet das Band zwischen Erzeuger und Kind, um eine mentale Brücke aufzubauen, die es dem Kind gestattet, eine telepathische Verbindung herzustellen, um über große Distanz kommunizieren. Wie einige andere Rituale, wird auch dieses in diesen Nächten der Abhörgeräte und elektronischen Überwachung wieder häufiger verwendet.",
    "ingredients": "ein Objekt, das einst dem Erzeuger gehörte, und eine silberne Schüssel mit klarem Wasser.",
    "execution": "Der Thaumaturg legt das Objekt ins Wasser und träufelt sein Blut in die Schüssel, während er sich maximal 30 Minuten lang auf die letzte Erinnerung an seinen Erzeuger konzentriert.",
    "system": "Sobald 15 Minuten verstrichen sind, wird die Ritualprobe abgelegt. Bei einem Triumph kann 10 Minuten lang in beide Richtung mental kommuniziert werden, sobald weitere 15 Minuten vergangen sind. Bei einem kritischen Triumph ist die Kommunikation augenblicklich möglich. Eine größere Störung auf einer der beiden Seiten unterbricht die Verbindung."
  },
  {
    "id": 7,
    "level": 2,
    "name": "Augen von Babel",
    "description": "Indem sie die Zunge und einen Augapfel einer Person verspeist, erlangt der Vampir die Fähigkeit, jede Sprache zu lesen und zu sprechen, die dem Opfer bekannt ist.",
    "ingredients": "ein frischer Augapfel und die Zunge einer Person.",
    "execution": "Die Zutaten werden dem Opfer frisch entnommen und von dem Vampir gekaut und verschluckt. (Damit holt er sich höchstwahrscheinlich einen Makel.)",
    "system": "Der Wallungs-Check, der für dieses Ritual erforderlich ist, sorgt dafür, dass die Zutaten sich auf übernatürliche Weise auflösen, sobald sie geschluckt wurden. Lege anschließend die Ritualprobe ab. Bei einem Triumph erhält der Zaubernde eine Woche lang die Fähigkeit, jede Sprache auf demselben Niveau wie das Opfer zu lesen und zu sprechen, die das Opfer kennt. Bei einem kritischen Triumph verlängert sich die Wirkung auf einen Monat."
  },
  {
    "id": 8,
    "level": 2,
    "name": "Erleuchtete Fährte des Blutes",
    "description": "Das Ritual gestattet es dem Thaumaturgen, die ehemaligen Aufenthaltsorte einer bestimmten Person als schwach leuchtenden Pfad wahrzunehmen, der nur für ihn sichtbar ist.",
    "ingredients": "ein weißes Satinband.",
    "execution": "Der Durchführende des Rituals taucht das Band in sein eigenes Blut und entzündet es.",
    "system": "Bei einem Triumph aus der Ritualprobe fängt das Band Feuer, obwohl es durchnässt ist, und brennt lichterloh wie eine Zündschnur. Sobald das Band verbrannt ist, tritt die Wirkung des Rituals ein. Solange das Ritual wirkt, kann der Vampir der schwachen Spur des Opfers folgen, selbst an Orten, an denen es keine Spuren hinterlassen hat, wie dicht bevölkerten Städten. Um der Spur zu folgen, würfelt der Vampir auf Intelligenz + Überleben bei einer Schwierigkeit von 6 minus der Differenz bei der Ritualprobe. Der Vampir muss das Opfer vom Sehen her kennen und kann den Weg zurückverfolgen, den das Opfer in den vergangenen 24 Stunden zurückgelegt hat. Der Pfad bleibt eine Nacht lang sichtbar. Bei einem kritischen Triumph verlängert sich die Wirkung auf zwei Nächte."
  },
  {
    "id": 9,
    "level": 2,
    "name": "Wahrheit des Blutes",
    "description": "Bis vor kurzem nur den Wesiren der Banu Haqim bekannt, erschafft dieses Ritual einen Trank, der Lügen von der Wahrheit trennt. Dieses Ritual hat die Kraft, dem Sprecher manchmal sogar Fakten zu entlocken, die ihm selbst bislang unbekannt waren.",
    "ingredients": "ein halber Liter Blut vom Opfer.",
    "execution": "Der Durchführende des Rituals mischt sein Blut mit dem des Opfers in einem Behälter, der groß genug ist, dass er einen Finger hineinstecken kann.",
    "system": "Statt der üblichen Ritualprobe taucht der Thaumaturg seinen Finger in die Mixtur und würfelt bei jeder Aussage des Opfers auf Entschlossenheit + Blutmagie vs. Fassung + Okkultismus. Schlägt der Wettbewerb einmal fehl, endet das Ritual. Bei einem Triumph erfährt er, ob die Aussage aus Sicht des Opfers stimmt. Bei einem kritischen Triumph durch den Zaubernden führt das Opfer seine Aussage näher aus und liefert weitere Informationen, selbst Einzelheiten, die es nur beiläufig bemerkt und unbewusst wieder vergessen hat. (Die Erzählerin sollte dem Spieler mitteilen, wenn es zu dem Thema keine weiteren Informationen gibt.) Die Mixtur brodelt und schäumt während der Durchführung und verwandelt sich am Ende der Szene zu Asche. Mit diesem Ritual können nicht Erinnerung vernebeln, Vergesslicher Geist oder andere erinnerungslöschende Kräfte durchdrungen werden. Der Thaumaturg kann die Ursache einer nicht vorhandenen oder trüben Erinnerung erraten, aber nicht die eigentliche Erinnerung zurückholen."
  },
  {
    "id": 10,
    "level": 2,
    "name": "Schutzzeichen gegen Geister",
    "description": "Mit diesem Ritual wird ein Gegenstand gegen körperlose Wesen wie Todesalben, Geister und elementare Geister geschützt. Jeder Versuch ihrerseits, den Gegenstand zu beeinflussen oder ihn zu durchdringen, löst die Wirkung aus. Dieses Schutzzeichen verwendet die Standardregeln für Schutzzeichen (S. 255).",
    "ingredients": "eine Handvoll Salz (in manchen Varianten stattdessen eine Handvoll Ziegelstaub) gemischt mit dem Blut der Zaubernden.",
    "execution": "",
    "system": ""
  },
  {
    "id": 11,
    "level": 2,
    "name": "Schutzkreis gegen Ghule",
    "description": "Mit diesem Ritual erschafft man ein kreisrundes Schutzzeichen auf dem Boden, um Ghulen den Weg zu versperren. Dieses Schutzzeichen verwendet die Standardregeln für Schutzkreise (S. 255).",
