=== VicarTeam/VicarData/$schemas/Disciplines.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "levels": {
          "type": "object",
          "patternProperties": {
            "^[0-9]+$": {
              "type": "array",
              "items": { "$ref": "#/definitions/IDisciplineAbility" }
            }
          },
          "additionalProperties": false
        },
        "note": {
          "type": "string"
        }
      },
      "required": ["id", "name", "levels"],
      "additionalProperties": false
    },
    "definitions": {
      "IDisciplineAbility": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "combination": {
            "$ref": "#/definitions/IDisciplineCombo"
          },
          "requirement": {
            "type": "number"
          },
          "minBloodPotency": {
            "type": "number"
          },
          "summary": {
            "type": "string"
          },
          "costs": {
            "type": "string"
          },
          "diceSupplies": {
            "type": "string"
          },
          "system": {
            "type": "string"
          },
          "alternatives": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "duration": {
            "type": "string"
          },
          "multiple": {
            "type": "boolean",
            "default": false
          }
        },
        "required": ["id", "name", "summary", "costs", "system", "duration"],
        "additionalProperties": false
      },
      "IDisciplineCombo": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "level": {
            "type": "number"
          }
        },
        "required": ["id", "level"],
        "additionalProperties": false
      }
    }
  }

=== VicarTeam/VicarData/en-US/Disciplines.json
[
  {
    "id": 1,
    "name": "Auspex",
    "summary": "One of the greatest gifts and worst curses that haunt vampires, the discipline Auspex allows kindred to discern the truth among all the lies, to test the minds of those around them, and to perceive reality as other beings on another plane. What at first appears to be the ultimate power of foresight and vision, perhaps bestows too much knowledge upon its users. They may be able to detect an assassin's blade before it strikes or enter an enemy's mind to turn it upside down, but they also sense every emotion, good and bad, see things they would prefer not to see, and discern a future they would rather not take a closer look at. Those who use Auspex open the door to paranoia, but using it is addictive. Once you know that the truth is within your grasp, you will seize any opportunity to reveal it. Kindred use Auspex in many ways. Some vampires act as spies for their court or faction. Others act on their own, blackmailing mortals or immortals with the secrets they have gleaned from quiet conversations, subtle sentients, and telepathic intrusions. Auspex allows the user to assume the role of detective in their own domain, investigating the scene of a vampire's destruction for telltale spiritual clues or interrogating suspects with supernatural accuracy.",
    "levels": {
      "1": [
        {
          "id": 1,
          "name": "Heightened Senses",
          "summary": "The vampire’s senses sharpen to a preternatural degree, giving them the ability to see in pitch darkness, hear ultrasonic frequencies and smell the fear of cowering prey.",
          "costs": "Free (but see below)",
          "diceSupplies": "Wits + Resolve",
          "system": "The user adds their Auspex rating to all perception rolls. If exposed to extreme sensations, such as loud bangs, flashes of intense light or overpowering smells while the power is active the user must succeed on a Wits + Resolve (Difficulty 3 or more) roll to dampen their senses in time, or the overload causes them to sustain a -3 dice penalty to all perception-based rolls for the rest of the scene.",
          "duration": "Until deactivated. Having the power active for longer stretches of time without rest (more than a scene), especially so for high-stimulus environments, might necessitate spending Willpower, at the Storyteller’s discretion."
        },
        {
          "id": 2,
          "name": "Sense the Unseen",
          "summary": "The senses of the vampire become attuned to dimensions beyond the mundane, allowing them to sense presences otherwise hidden from the naked eye. This can be anything from another vampire using Obfuscate to someone using Auspex to spy upon the character to a ghost in the middle of the room. Dormant Blood Sorcery spells and rituals might also be found with this power, at the Storyteller’s discretion.",
          "costs": "Free",
          "diceSupplies": "Wits + Auspex or Resolve + Auspex",
          "system": "Whenever there’s something supernatural hiding in plain sight, the Storyteller makes a hidden roll of Wits + Auspex against a Difficulty they choose. Against an entity actively trying to stay hidden, the Storyteller can call for a blind roll (“Lisa, roll seven dice for me”) as a contest against the target’s relevant pool. (For example, detecting a vampire using Obfuscate would be a roll of Wits + Auspex vs Wits + Obfuscate) If the vampire actively searches for a hidden supernatural entity, they roll Resolve + Auspex similarly.",
          "duration": "passive"
        }
      ],
      "2": [
        {
          "id": 3,
          "name": "Premonition",
          "summary": "The vampire experiences flashes of insight. These may take the form of raised hackles, sudden inspiration or even vivid visions. While never too precise, these visions can nudge the vampire out of harm’s way or reveal a truth previously overlooked.",
          "costs": "Free or one Rouse Check",
          "diceSupplies": "Resolve + Auspex",
          "system": "Whenever the Storyteller deems it appropriate, this power gives the character a sudden hint that aids them in some way: letting them find a clue they’ve missed or saving them from danger. Whether it gives the character a sudden vision of themselves walking into a trap, an inviting red glow over the second right turn during a chase, or the brief flash of a skeleton beneath the floorboards in the Prince’s office, this power always gives the Storyteller license to subtly speed up play or move the story onto a desired track. The suggested limit is one premonition per scene, even if more than one character has Premonition.",
          "alternatives": [
            "The user can also actively provoke a premonition by focusing on a subject, making a Rouse Check and rolling Resolve + Auspex. The number of successes rolled determines the level of insight on the subject, if any."
          ],
          "duration": "passive"
        }
      ],
      "3": [
        {
          "id": 4,
          "name": "Scry the Soul",
          "summary": "By focusing on a person, the v ampire can perceive the state of that person’s psyche as a shifting aur a of colors. Auras reveal little precise information, but do provide clues regarding many subjects, e.g., emotional state, Resonance, and supernatural traits. If looking for a specific condition, the vampire can cursorily scan the crowd to detect it. Such cursory scans provide no further information.",
          "costs": "One Rouse Check",
          "diceSupplies": "Intelligence + Auspex vs Composure + Subterfuge",
          "system": "Make an Intelligence + Auspex vs Composure + Subterfuge roll. On a win, the Storyteller truthfully answers a number of questions equal to the margin of the roll about the target’s aura and psyche, including:<br/>◻ The emotional state of the subject.<br/>◻ The Resonance in the subject’s blood<br/>◻ Whether the subject is a vampire, werewolf, ghoul or any other supernatural being<br/>◻ Whether the subject is under the influence of Blood Sorcery or other magic<br/>◻ Whether the subject has committed diablerie in the last year<br/>◻ A critical win allows discovery of something unexpected, as determined by the Storyteller<br/>If scanning a crowd, roll versus a Difficulty determined by the size of the crowd and external distractions, as well as the type of trait being sought. (Finding the vampire in the living room might only be a Difficulty 3, while finding the most nervous person at a crowded rave is most likely Difficulty 6 or higher.)",
          "duration": "One turn, or Storyteller’s discretion"
        },
        {
          "id": 5,
          "name": "Share the Senses",
          "summary": "By reaching out with their mind, the vampire can tap into the senses of another mortal or v ampire, seeing, hearing, and feeling what they do. The user still retains their own perceptions and is still aware of their own surroundings, though the effect requires some getting used to. The user decides whether to tap into only one, some, or all of the target’s senses. When used on a stranger this power requires line of sight to initiate. However, it can be used over longer distances on someone who still has some of the user’s Blood in their body.",
          "costs": "One Rouse Check",
          "diceSupplies": "Resolve + Auspex",
          "system": "Roll Resolve + Auspex at Difficulty 3. This Difficulty can go up depending on distraction, distance, and other factors, such as the amount of the user’s Blood that remains in the target. The target usually remains unaware of the intrusion, but Sense the Unseen can allow the passenger to be noticed. To get rid of an unwanted rider, the victim must beat the intruder at a Wits + Resolve vs Wits + Resolve roll. An Auspex user thrown out this way cannot make another Sharing attempt until the next night.",
          "duration": "One scene"
        }
      ],
      "4": [
        {
          "id": 6,
          "name": "Spirit's Touch",
          "summary": "By touching an inanimate object or the ground at a location, the vampire can sense the emotional residue left by those who have handled that object or visited the location in the past. The user gains insight into not only that person, but also what was done and under what circumstances. While rarely crystal clear, the information often provides leads impossible to gain from regular forensics and deduction.",
          "costs": "One Rouse Check",
          "diceSupplies": "Intelligence + Auspex",
          "system": "Make an Intelligence + Auspex roll versus a Difficulty depending on the information sought. Gleaning the emotional state of the user of a murder weapon used a few days before is Difficulty 3, but sensing the surroundings in which a 300-year old letter was written approaches Difficulty 6 or higher. Each point of margin on the roll allows the user to sense roughly one additional previous handler and set of circumstances, counting backwards from the most recent.",
          "duration": "One turn"
        }
      ],
      "5": [
        {
          "id": 7,
          "name": "Clairvoyance",
          "summary": "By closing their eyes and entering a light trance, the vampire becomes master of its surroundings. In a few minutes it can gather information from roughly a city-block sized area (more if outdoors or less populated) that would normally take many hours, perhaps days of legwork and investigation. Once connected in such a way to their surroundings the vampire can also receive information on anything happening out of the ordinary in the area.",
          "costs": "One Rouse Check",
          "diceSupplies": "Intelligence + Auspex",
